# syntax=docker/dockerfile:1
FROM node:22-alpine AS build
WORKDIR /app
COPY hms-frontend/package*.json ./
RUN npm install --legacy-peer-deps
COPY hms-frontend .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
