aws_region       = "us-east-1"
environment     = "prod"
vpc_cidr        = "10.0.0.0/16"
public_subnets  = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnets = ["10.0.3.0/24", "10.0.4.0/24"]
availability_zones = ["us-east-1a", "us-east-1b"]
db_username     = "hmsadmin"
db_password     = "secure_password_123"  # Use AWS Secrets Manager in production
db_instance_class = "db.m5.large"
cluster_name    = "hms-production-cluster"
