# Generated by Django 5.2.5 on 2025-08-17 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("max_users", models.PositiveIntegerField(default=10)),
                ("enable_opd", models.BooleanField(default=True)),
                ("enable_ipd", models.BooleanField(default=True)),
                ("enable_diagnostics", models.BooleanField(default=True)),
                ("enable_pharmacy", models.BooleanField(default=True)),
                ("enable_accounting", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="HospitalPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enable_opd", models.BooleanField(blank=True, null=True)),
                ("enable_ipd", models.BooleanField(blank=True, null=True)),
                ("enable_diagnostics", models.BooleanField(blank=True, null=True)),
                ("enable_pharmacy", models.BooleanField(blank=True, null=True)),
                ("enable_accounting", models.BooleanField(blank=True, null=True)),
                (
                    "hospital",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="hospitals.plan"
                    ),
                ),
            ],
        ),
    ]
