# Generated by Django 4.2.23 on 2025-08-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="bill",
            name="bill_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="billlineitem",
            name="bli_dept_idx",
        ),
    ]
